language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - sudo -E bash ./gate/travis-vault.sh
install:
  - pip install -r requirements.txt -c https://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt
  - pip install -r test-requirements.txt -c https://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt
script:
  - flake8
  - stestr run "^vaultlocker.tests.unit.*"
  - pifpaf run vault -- stestr run "^vaultlocker.tests.functional.*"
